"""add_user_interaction_tracking

Revision ID: 13355a98a7a6
Revises: 6666f3f276aa
Create Date: 2026-01-07 16:34:55.119838

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "13355a98a7a6"
down_revision: str | None = "6666f3f276aa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
