"""add_sample_commercial_products

Revision ID: 6666f3f276aa
Revises: c0aac89723f0
Create Date: 2026-01-07 16:25:56.695925

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6666f3f276aa"
down_revision: str | None = "c0aac89723f0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_auditlog_action"), table_name="auditlog")
    op.drop_index(op.f("ix_auditlog_record_id"), table_name="auditlog")
    op.drop_index(op.f("ix_auditlog_table_name"), table_name="auditlog")
    op.drop_index(op.f("ix_auditlog_timestamp"), table_name="auditlog")
    op.drop_index(op.f("ix_auditlog_user_id"), table_name="auditlog")
    op.drop_table("auditlog")
    op.drop_index(op.f("ix_userassethistory_asset_id"), table_name="userassethistory")
    op.drop_index(op.f("ix_userassethistory_changed_at"), table_name="userassethistory")
    op.drop_index(
        op.f("ix_userassethistory_is_valid_from"), table_name="userassethistory"
    )
    op.drop_index(
        op.f("ix_userassethistory_is_valid_to"), table_name="userassethistory"
    )
    op.drop_index(op.f("ix_userassethistory_user_id"), table_name="userassethistory")
    op.drop_table("userassethistory")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "userassethistory",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("asset_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "asset_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column("name", sa.VARCHAR(length=200), autoincrement=False, nullable=False),
        sa.Column(
            "value",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("is_confirmed", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "extra_data",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "change_reason", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
        sa.Column("changed_by", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "changed_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "is_valid_from",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "is_valid_to", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"], ["userasset.id"], name=op.f("userassethistory_asset_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("userassethistory_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("userassethistory_pkey")),
    )
    op.create_index(
        op.f("ix_userassethistory_user_id"),
        "userassethistory",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_userassethistory_is_valid_to"),
        "userassethistory",
        ["is_valid_to"],
        unique=False,
    )
    op.create_index(
        op.f("ix_userassethistory_is_valid_from"),
        "userassethistory",
        ["is_valid_from"],
        unique=False,
    )
    op.create_index(
        op.f("ix_userassethistory_changed_at"),
        "userassethistory",
        ["changed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_userassethistory_asset_id"),
        "userassethistory",
        ["asset_id"],
        unique=False,
    )
    op.create_table(
        "auditlog",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "table_name", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column("record_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "action",
            postgresql.ENUM("CREATE", "UPDATE", "DELETE", name="auditaction"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "user_type",
            sa.VARCHAR(length=50),
            server_default=sa.text("'user'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "old_values",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "new_values",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "ip_address", sa.VARCHAR(length=45), autoincrement=False, nullable=True
        ),
        sa.Column(
            "user_agent", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
        sa.Column(
            "session_id", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "extra_metadata",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("auditlog_pkey")),
    )
    op.create_index(op.f("ix_auditlog_user_id"), "auditlog", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_auditlog_timestamp"), "auditlog", ["timestamp"], unique=False
    )
    op.create_index(
        op.f("ix_auditlog_table_name"), "auditlog", ["table_name"], unique=False
    )
    op.create_index(
        op.f("ix_auditlog_record_id"), "auditlog", ["record_id"], unique=False
    )
    op.create_index(op.f("ix_auditlog_action"), "auditlog", ["action"], unique=False)
    # ### end Alembic commands ###
