"""optimize_action_plan_models_final

Revision ID: 783522505fe3
Revises: cf972a7df55d
Create Date: 2026-01-23 22:20:26.454224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '783522505fe3'
down_revision: Union[str, None] = 'cf972a7df55d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Create new table action_plan_step (Table already exists, skipping)
    # op.create_table('action_plan_step',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('plan_id', sa.Integer(), nullable=False),
    # sa.Column('step_number', sa.Integer(), nullable=True),
    # sa.Column('action', sa.String(length=500), nullable=False),
    # sa.Column('description', sa.Text(), nullable=True),
    # sa.Column('expected_outcome', sa.String(length=500), nullable=True),
    # sa.Column('timeline', sa.String(length=200), nullable=True),
    # sa.Column('status', sa.String(length=20), nullable=True),
    # sa.Column('completed_at', sa.DateTime(), nullable=True),
    # sa.Column('user_notes', sa.Text(), nullable=True),
    # sa.ForeignKeyConstraint(['plan_id'], ['action_plan.id'], ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_action_plan_step_plan_id'), 'action_plan_step', ['plan_id'], unique=False)
    
    # 2. Update action_plan table
    op.add_column('action_plan', sa.Column('original_steps_snapshot', sa.JSON(), nullable=True))
    op.add_column('action_plan', sa.Column('adopted_at', sa.DateTime(), nullable=True))
    op.add_column('action_plan', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.drop_column('action_plan', 'steps')
    op.drop_column('action_plan', 'completed_steps')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Revert action_plan changes
    op.add_column('action_plan', sa.Column('completed_steps', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('action_plan', sa.Column('steps', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('action_plan', 'completed_at')
    op.drop_column('action_plan', 'adopted_at')
    op.drop_column('action_plan', 'original_steps_snapshot')
    
    # Drop action_plan_step table
    op.drop_index(op.f('ix_action_plan_step_plan_id'), table_name='action_plan_step')
    op.drop_table('action_plan_step')
    # ### end Alembic commands ###