"""fix_interaction_metadata_field_name

Revision ID: 7de2c363f342
Revises: 13355a98a7a6
Create Date: 2026-01-07 16:40:02.534561

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "7de2c363f342"
down_revision: str | None = "13355a98a7a6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
