"""Add dismiss_reason to action_plan

Revision ID: a3107599d434
Revises: 783522505fe3
Create Date: 2026-01-24 23:38:41.190427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3107599d434'
down_revision: Union[str, None] = '783522505fe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action_plan', sa.Column('dismiss_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('action_plan', 'dismiss_reason')
    # ### end Alembic commands ###
    op.drop_column('action_plan', 'dismiss_reason')
    # ### end Alembic commands ###