"""Add knowledge models

Revision ID: a665f378fe1d
Revises: add_unknown_uppercase_risklevel
Create Date: 2026-01-21 13:58:55.489047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a665f378fe1d'
down_revision: Union[str, None] = 'add_unknown_uppercase_risklevel'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create Enums manually
    knowledge_category = postgresql.ENUM('POLICY', 'PROVIDENT_FUND', 'TAX', 'LOAN', 'FAQ', 'PRODUCT', 'GENERAL', name='knowledgecategory')
    knowledge_category.create(op.get_bind(), checkfirst=True)
    
    knowledge_status = postgresql.ENUM('ACTIVE', 'DEPRECATED', 'DRAFT', name='knowledgestatus')
    knowledge_status.create(op.get_bind(), checkfirst=True)
    
    op.drop_index(op.f('idx_usercognition_last_analyzed'), table_name='usercognition')
    op.drop_index(op.f('ix_usercognition_user_id'), table_name='usercognition')
    op.drop_table('usercognition')
    op.alter_column('faq_knowledge', 'answer',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('faq_knowledge', 'category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('POLICY', 'PROVIDENT_FUND', 'TAX', 'LOAN', 'FAQ', 'PRODUCT', 'GENERAL', name='knowledgecategory'),
               existing_nullable=False,
               postgresql_using='category::knowledgecategory')
               
    # Drop default first
    op.alter_column('faq_knowledge', 'status', server_default=None)
    
    op.alter_column('faq_knowledge', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('ACTIVE', 'DEPRECATED', 'DRAFT', name='knowledgestatus'),
               existing_nullable=False,
               server_default=sa.text("'ACTIVE'::knowledgestatus"),
               postgresql_using='status::knowledgestatus')
               
    op.alter_column('policy_knowledge', 'category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('POLICY', 'PROVIDENT_FUND', 'TAX', 'LOAN', 'FAQ', 'PRODUCT', 'GENERAL', name='knowledgecategory'),
               existing_nullable=False,
               postgresql_using='category::knowledgecategory')
               
    # Drop default first
    op.alter_column('policy_knowledge', 'status', server_default=None)
    
    op.alter_column('policy_knowledge', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('ACTIVE', 'DEPRECATED', 'DRAFT', name='knowledgestatus'),
               existing_nullable=False,
               server_default=sa.text("'ACTIVE'::knowledgestatus"),
               postgresql_using='status::knowledgestatus')
               
    op.alter_column('policy_knowledge', 'content',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('product_knowledge', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
               
    # Drop default first
    op.alter_column('product_knowledge', 'status', server_default=None)
    
    op.alter_column('product_knowledge', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('ACTIVE', 'DEPRECATED', 'DRAFT', name='knowledgestatus'),
               existing_nullable=False,
               server_default=sa.text("'ACTIVE'::knowledgestatus"),
               postgresql_using='status::knowledgestatus')
    op.drop_index(op.f('ix_real_estate_asset_city'), table_name='real_estate_asset')
    op.drop_index(op.f('idx_user_cognition_last_analyzed'), table_name='user_cognition')
    op.drop_constraint(op.f('user_cognition_user_id_key'), 'user_cognition', type_='unique')
    op.create_index(op.f('ix_user_cognition_user_id'), 'user_cognition', ['user_id'], unique=True)
    # op.drop_index(op.f('ix_vector_memory_embedding_cosine'), table_name='vector_memory', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index(op.f('ix_vector_memory_embedding_cosine'), 'vector_memory', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_user_cognition_user_id'), table_name='user_cognition')
    op.create_unique_constraint(op.f('user_cognition_user_id_key'), 'user_cognition', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_user_cognition_last_analyzed'), 'user_cognition', ['user_id', 'last_analyzed_message_id'], unique=False)
    op.create_index(op.f('ix_real_estate_asset_city'), 'real_estate_asset', ['city'], unique=False)
    op.alter_column('product_knowledge', 'status',
               existing_type=sa.Enum('ACTIVE', 'DEPRECATED', 'DRAFT', name='knowledgestatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('product_knowledge', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('policy_knowledge', 'content',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('policy_knowledge', 'status',
               existing_type=sa.Enum('ACTIVE', 'DEPRECATED', 'DRAFT', name='knowledgestatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('policy_knowledge', 'category',
               existing_type=sa.Enum('POLICY', 'PROVIDENT_FUND', 'TAX', 'LOAN', 'FAQ', 'PRODUCT', 'GENERAL', name='knowledgecategory'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('faq_knowledge', 'status',
               existing_type=sa.Enum('ACTIVE', 'DEPRECATED', 'DRAFT', name='knowledgestatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('faq_knowledge', 'category',
               existing_type=sa.Enum('POLICY', 'PROVIDENT_FUND', 'TAX', 'LOAN', 'FAQ', 'PRODUCT', 'GENERAL', name='knowledgecategory'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('faq_knowledge', 'answer',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_table('usercognition',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('financial_goals', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('risk_profile', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('collection_status', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('advisor_note', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('last_analyzed_message_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_memory_extraction_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('usercognition_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('usercognition_pkey'))
    )
    op.create_index(op.f('ix_usercognition_user_id'), 'usercognition', ['user_id'], unique=True)
    op.create_index(op.f('idx_usercognition_last_analyzed'), 'usercognition', ['user_id', 'last_analyzed_message_id'], unique=False)
    # ### end Alembic commands ###