"""Add audit trail and validation constraints

Revision ID: c0aac89723f0
Revises: e6148c4db9fe
Create Date: 2026-01-07 11:36:26.594419

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c0aac89723f0"
down_revision: str | None = "e6148c4db9fe"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create audit action enum if it doesn't exist
    op.execute(
        "DO $$ BEGIN CREATE TYPE auditaction AS ENUM ('CREATE', 'UPDATE', 'DELETE'); EXCEPTION WHEN duplicate_object THEN null; END $$;"
    )

    # Create audit log table
    op.create_table(
        "auditlog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("table_name", sa.String(length=100), nullable=False),
        sa.Column("record_id", sa.Integer(), nullable=False),
        sa.Column(
            "action",
            sa.Enum("CREATE", "UPDATE", "DELETE", name="auditaction"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column(
            "user_type", sa.String(length=50), nullable=False, server_default="user"
        ),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("old_values", sa.JSON(), nullable=True),
        sa.Column("new_values", sa.JSON(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("session_id", sa.String(length=100), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    # Create indexes for audit log
    op.create_index("ix_auditlog_table_name", "auditlog", ["table_name"])
    op.create_index("ix_auditlog_record_id", "auditlog", ["record_id"])
    op.create_index("ix_auditlog_user_id", "auditlog", ["user_id"])
    op.create_index("ix_auditlog_timestamp", "auditlog", ["timestamp"])
    op.create_index("ix_auditlog_action", "auditlog", ["action"])

    # Create user asset history table
    op.create_table(
        "userassethistory",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("asset_type", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("is_confirmed", sa.Boolean(), nullable=False),
        sa.Column("extra_data", sa.JSON(), nullable=True),
        sa.Column("change_reason", sa.String(length=500), nullable=True),
        sa.Column("changed_by", sa.Integer(), nullable=True),
        sa.Column("changed_at", sa.DateTime(), nullable=False),
        sa.Column("is_valid_from", sa.DateTime(), nullable=False),
        sa.Column("is_valid_to", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["userasset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # Create indexes for user asset history
    op.create_index("ix_userassethistory_asset_id", "userassethistory", ["asset_id"])
    op.create_index("ix_userassethistory_user_id", "userassethistory", ["user_id"])
    op.create_index(
        "ix_userassethistory_changed_at", "userassethistory", ["changed_at"]
    )
    op.create_index(
        "ix_userassethistory_is_valid_from", "userassethistory", ["is_valid_from"]
    )
    op.create_index(
        "ix_userassethistory_is_valid_to", "userassethistory", ["is_valid_to"]
    )

    # Add validation constraints

    # Phone number validation (basic format check)
    op.execute("""
        ALTER TABLE "user"
        ADD CONSTRAINT check_phone_format
        CHECK (phone ~ '^[+]?[0-9]{10,15}$')
    """)

    # Asset value must be positive
    op.execute("""
        ALTER TABLE userasset
        ADD CONSTRAINT check_asset_value_positive
        CHECK (value > 0)
    """)

    # Asset name cannot be empty
    op.execute("""
        ALTER TABLE userasset
        ADD CONSTRAINT check_asset_name_not_empty
        CHECK (length(trim(name)) > 0)
    """)

    # User profile monthly expense must be non-negative if provided
    op.execute("""
        ALTER TABLE userprofile
        ADD CONSTRAINT check_monthly_expense_non_negative
        CHECK (monthly_expense IS NULL OR monthly_expense >= 0)
    """)

    # Commercial product priority must be positive
    op.execute("""
        ALTER TABLE commercialproduct
        ADD CONSTRAINT check_priority_positive
        CHECK (priority > 0)
    """)

    # Commercial product name cannot be empty
    op.execute("""
        ALTER TABLE commercialproduct
        ADD CONSTRAINT check_product_name_not_empty
        CHECK (length(trim(name)) > 0)
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop validation constraints
    op.execute(
        "ALTER TABLE commercialproduct DROP CONSTRAINT IF EXISTS check_product_name_not_empty"
    )
    op.execute(
        "ALTER TABLE commercialproduct DROP CONSTRAINT IF EXISTS check_priority_positive"
    )
    op.execute(
        "ALTER TABLE userprofile DROP CONSTRAINT IF EXISTS check_monthly_expense_non_negative"
    )
    op.execute(
        "ALTER TABLE userasset DROP CONSTRAINT IF EXISTS check_asset_name_not_empty"
    )
    op.execute(
        "ALTER TABLE userasset DROP CONSTRAINT IF EXISTS check_asset_value_positive"
    )
    op.execute('ALTER TABLE "user" DROP CONSTRAINT IF EXISTS check_phone_format')

    # Drop indexes
    op.drop_index("ix_userassethistory_is_valid_to", table_name="userassethistory")
    op.drop_index("ix_userassethistory_is_valid_from", table_name="userassethistory")
    op.drop_index("ix_userassethistory_changed_at", table_name="userassethistory")
    op.drop_index("ix_userassethistory_user_id", table_name="userassethistory")
    op.drop_index("ix_userassethistory_asset_id", table_name="userassethistory")
    op.drop_index("ix_auditlog_action", table_name="auditlog")
    op.drop_index("ix_auditlog_timestamp", table_name="auditlog")
    op.drop_index("ix_auditlog_user_id", table_name="auditlog")
    op.drop_index("ix_auditlog_record_id", table_name="auditlog")
    op.drop_index("ix_auditlog_table_name", table_name="auditlog")

    # Drop tables
    op.drop_table("userassethistory")
    op.drop_table("auditlog")

    # Drop enum
    op.execute("DROP TYPE auditaction")

    # ### end Alembic commands ###
