"""add_chat_message_table

Revision ID: d597c13bb774
Revises: 7de2c363f342
Create Date: 2026-01-13 17:26:55.672311

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d597c13bb774"
down_revision: Union[str, None] = "7de2c363f342"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_userinteraction_created_at"), table_name="userinteraction")
    op.drop_index(
        op.f("ix_userinteraction_interaction_type"), table_name="userinteraction"
    )
    op.drop_index(op.f("ix_userinteraction_product_id"), table_name="userinteraction")
    op.drop_index(op.f("ix_userinteraction_session_id"), table_name="userinteraction")
    op.drop_index(op.f("ix_userinteraction_user_id"), table_name="userinteraction")
    op.drop_table("userinteraction")
    op.drop_table("auditlog")
    op.drop_table("userassethistory")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "userassethistory",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("asset_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "asset_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column("name", sa.VARCHAR(length=200), autoincrement=False, nullable=False),
        sa.Column(
            "value",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("is_confirmed", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "extra_data",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "change_reason", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
        sa.Column("changed_by", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "changed_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "is_valid_from", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "is_valid_to", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"], ["userasset.id"], name=op.f("userassethistory_asset_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("userassethistory_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("userassethistory_pkey")),
    )
    op.create_table(
        "auditlog",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "table_name", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column("record_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "action",
            postgresql.ENUM("CREATE", "UPDATE", "DELETE", name="auditaction"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "user_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "timestamp", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "old_values",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "new_values",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "ip_address", sa.VARCHAR(length=45), autoincrement=False, nullable=True
        ),
        sa.Column(
            "user_agent", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
        sa.Column(
            "session_id", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "extra_metadata",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("auditlog_pkey")),
    )
    op.create_table(
        "userinteraction",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("product_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "interaction_type",
            postgresql.ENUM(
                "VIEW", "CLICK", "CONTACT", "DISMISS", "SHARE", name="interactiontype"
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "interaction_metadata",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("session_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["commercialproduct.id"],
            name=op.f("userinteraction_product_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("userinteraction_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("userinteraction_pkey")),
    )
    op.create_index(
        op.f("ix_userinteraction_user_id"), "userinteraction", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_userinteraction_session_id"),
        "userinteraction",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_userinteraction_product_id"),
        "userinteraction",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_userinteraction_interaction_type"),
        "userinteraction",
        ["interaction_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_userinteraction_created_at"),
        "userinteraction",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###
