"""add_wealth_models

Revision ID: e38f1ff9b7d4
Revises: a3107599d434
Create Date: 2026-02-08 12:11:45.612159

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e38f1ff9b7d4"
down_revision: Union[str, None] = "a3107599d434"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create CashFlowItem table
    op.create_table('cash_flow_item',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('flow_type', sa.String(), nullable=False),
        sa.Column('frequency', sa.String(), nullable=False),
        sa.Column('is_recurring', sa.Boolean(), nullable=False),
        sa.Column('recurrence_day', sa.Integer(), nullable=True),
        sa.Column('related_asset_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['related_asset_id'], ['userasset.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_flow_item_user_id'), 'cash_flow_item', ['user_id'], unique=False)

    # Create AssetValuationHistory table
    op.create_table('asset_valuation_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('asset_id', sa.Integer(), nullable=False),
        sa.Column('date', sa.DateTime(), nullable=False),
        sa.Column('value', sa.Float(), nullable=False),
        sa.Column('source', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['asset_id'], ['userasset.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_valuation_history_asset_id'), 'asset_valuation_history', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_valuation_history_date'), 'asset_valuation_history', ['date'], unique=False)

    # Create WealthHistory table
    op.create_table('wealth_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('date', sa.DateTime(), nullable=False),
        sa.Column('total_assets', sa.Float(), nullable=False),
        sa.Column('total_liabilities', sa.Float(), nullable=False),
        sa.Column('net_worth', sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wealth_history_date'), 'wealth_history', ['date'], unique=False)
    op.create_index(op.f('ix_wealth_history_user_id'), 'wealth_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wealth_history_user_id'), table_name='wealth_history')
    op.drop_index(op.f('ix_wealth_history_date'), table_name='wealth_history')
    op.drop_table('wealth_history')
    op.drop_index(op.f('ix_asset_valuation_history_date'), table_name='asset_valuation_history')
    op.drop_index(op.f('ix_asset_valuation_history_asset_id'), table_name='asset_valuation_history')
    op.drop_table('asset_valuation_history')
    op.drop_index(op.f('ix_cash_flow_item_user_id'), table_name='cash_flow_item')
    op.drop_table('cash_flow_item')
    # ### end Alembic commands ###
