"""Add model validation constraints

Revision ID: e6148c4db9fe
Revises: eb0a9c8ddf6e
Create Date: 2026-01-06 18:25:26.870951

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "e6148c4db9fe"
down_revision: str | None = "eb0a9c8ddf6e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
